all: question1 question2 question3 question4 question5 question6 question7 question8

question1:
	gcc -Wall -Werror question1.c -g -o question1.tsk
question2:
	gcc -Wall -Werror question2.c -g -o question2.tsk
question3:
	gcc -Wall -Werror question3.c -g -o question3.tsk
question4:
	gcc -Wall -Werror question4.c -g -o question4.tsk
question5:
	gcc -Wall -Werror question5.c -g -o question5.tsk
question6:
	gcc -Wall -Werror question6.c -g -o question6.tsk
question7:
	gcc -Wall -Werror question7.c -g -o question7.tsk
question8:
	gcc -Wall -Werror question8.c -g -o question8.tsk

clean:
	rm -rf *.tsk
	rm -rf *.o

